apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
spec:
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  source:
    path: apps/helm-webapp
    repoURL: https://github.com/AverageGoldenRetrieverEnjoyer/cloud-manifests.git
    targetRevision: HEAD
    valueFiles:
      - values-prod.yaml
    helm:
      valueFiles:
        - values-dev.yaml
  sources: []
  project: default
  syncOptions:
    - CreateNamespace=true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
