apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
spec:
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  source:
    path: helm-webapp
    repoURL: https://github.com/devopsjourney1/argo-examples
    targetRevision: HEAD
    valueFiles:
      - values-prod.yaml
    helm:
      valueFiles:
        - values-dev.yaml
  sources: []
  project: default
  syncOptions:
    - CreateNamespace=true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
